@baseUrl = http://localhost:3000

#São apenas meus testes com o REST CLIENT
# MÓDULO: DISCIPLINA

### Criar Disciplina
POST {{baseUrl}}/disciplina/create
Content-Type: application/json

{
  "nomeDisciplina": "Programação Orientada a Objetos",
  "matriculaDisciplina": "BES-002"
}

### Listar Disciplinas
GET {{baseUrl}}/disciplina/all

### Atualizar Disciplina
PUT http://localhost:3000/disciplina/update
Content-Type: application/json

{
  "id": 1,
  "nomeDisciplina": "Engenharia de Software II (Atualizada)"
}

### Deletar Disciplina
DELETE http://localhost:3000/disciplina/delete
Content-Type: application/json

{
  "id": 1
}

# MÓDULO: PROFESSOR

### Criar Professor
POST {{baseUrl}}/professor/create
Content-Type: application/json

{
  "nomeProf": "Gutierrez",
  "emailProf": "Guti@prof.uepa.com",
  "matriculaProf": "PROF-02"
}

### Listar Professores
GET {{baseUrl}}/professor/all

### Atualizar Professor (ID vai no corpo do JSON)
PUT {{baseUrl}}/professor/update
Content-Type: application/json

{
  "id": 1,
  "nomeProf": "Tiago Nicolau"
}

### Deletar Professor (ID vai no corpo do JSON)
DELETE {{baseUrl}}/professor/delete
Content-Type: application/json

{
  "id": 1
}

# MÓDULO: SALA 

### 1. Criar uma Sala (CREATE)
POST http://localhost:3000/sala/create
Content-Type: application/json

{
  "nomeSala": "Laboratório de Informática 01",
  "tipoSala": "Laboratório"
}

### 2. Listar todas as Salas (READ)
GET http://localhost:3000/sala/all

### 3. Atualizar uma Sala (UPDATE)
PUT http://localhost:3000/sala/update
Content-Type: application/json

{
  "id": 1,
  "nomeSala": "Laboratório de Informática 01",
  "tipoSala": "Laboratório - Indisponível"
}

### 4. Deletar uma Sala (DELETE)
DELETE http://localhost:3000/sala/delete
Content-Type: application/json

{
  "id": 1
}

### Criar Curso
POST http://localhost:3000/curso/create
Content-Type: application/json

{
  "nomeCurso": "Biomedicina",
  "siglaCurso": "BIOMED"
}

### Listar Cursos
GET http://localhost:3000/curso/all

### 3. Atualizar Curso (UPDATE)
PUT http://localhost:3000/curso/update
Content-Type: application/json

{
  "id": 1, 
  "nomeCurso": "Engenharia de Software (Grade Nova)",
  "siglaCurso": "BES-NOVO"
}

### 4. Deletar Curso (DELETE)
DELETE http://localhost:3000/curso/delete
Content-Type: application/json

{
  "id": 4
}

# MÓDULO: ADMINISTRADOR (CRUD COMPLETO)

### 1. Criar Admin (CREATE)
POST http://localhost:3000/administrador/create
Content-Type: application/json

{
  "nomeAdm": "Admin 2",
  "emailAdm": "admin2@uepa.br",
  "senhaAdm": "admin123"
}

### 2. Listar Admins (READ)
GET http://localhost:3000/administrador/all

### 3. Atualizar Admin (UPDATE)
PUT http://localhost:3000/administrador/update
Content-Type: application/json

{
  "id": 1,
  "nomeAdm": "Admin Principal (Editado)",
  "senhaAdm": "novaSenha123"
}

### 4. Deletar Admin (DELETE)
DELETE http://localhost:3000/administrador/delete
Content-Type: application/json

{
  "id": 1
}

# MÓDULO: PERÍODO

### Criar Periodo
POST http://localhost:3000/periodo/create
Content-Type: application/json

{
  "semestre": "2025.1",
  "dataInicio": "2025-08-09T00:00:00.000Z",
  "dataFim": "2025-10-08T00:00:00.000Z",
  "descricao": "Primeiro Bimestre"
}

### Listar Periodos
GET http://localhost:3000/periodo/all

### Atualizar Periodo (UPDATE)
PUT http://localhost:3000/periodo/update
Content-Type: application/json

{
  "id": 1,
  "descricao": "1º Bimestre (Datas Ajustadas)",
  "dataFim": "2025-10-15T00:00:00.000Z"
}

### Deletar Periodo (DELETE)
DELETE http://localhost:3000/periodo/delete
Content-Type: application/json

{
  "id": 1
}

# MÓDULO: ALOCAÇÃO 

### Criar Horário
POST http://localhost:3000/alocacao/create
Content-Type: application/json

{
  "diaSemana": "Segunda",
  "horarioInicio": "07:30",
  "horarioFim": "10:00",
  "professorId": 1,
  "disciplinaId": 1,
  "salaId": 1,
  "cursoId": 1,
  "periodoId": 1
}

### Listar Horários (Veja a mágica do Include!)
GET http://localhost:3000/alocacao/all